apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-k8s-hpa
  namespace: lab-k8s
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-k8s
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
