name: Deploy do EKS via Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t guilota/app-k8s-lab:latest .
          docker push guilota/app-k8s-lab:latest

      - name: Configurar AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update kubeconfig EKS
        run: |
          aws eks --region us-east-2 update-kubeconfig --name gsreis-cluster

      - name: Criar Namespace
        run: kubectl apply -f k8s/namespace.yaml

      - name: Criar ConfigMap
        run: kubectl apply -f k8s/configmap.yaml

      - name: Criar Deployment
        run: kubectl apply -f k8s/deployment.yaml

      - name: Criar Service
        run: kubectl apply -f k8s/service.yaml
